### ISSUE TITLE
Is there any simple example as to how to utilize this tool? I just want to slice a java file with variable as parameter.

### ISSUE THREAD

**Issue by sourabhsparkala** [hammacher/javaslicer#5]
I am looking for a method or an example  

Which can slice the java file A.java with criterion <A.methodC, {a}>
Class A{
int a;
int b;

methodC(){
if(b>0){
    a=2;
}
}
}

Your help would be much appreciated.

**Comment by hammacher** [comment]
There is a "Usage" section in the readme which should cover this.
https://github.com/hammacher/javaslicer#usage
